add yaml file defining aggregate regions
epidemics/epimodel-covid-data pull request #12
Opened 2020-05-12 01:55 UTC by wolverdude

Adds a yaml file used in [eipimodel#49](https://github.com/epidemics/epimodel/pull/49).

2020-05-12 18:04 UTC, mathijshenquet commented
@wolverdude the one Jacob is using in production actually looks like this: 
https://github.com/epidemics/epimodel-covid-data/pull/13
https://github.com/epidemics/epimodel-covid-data/pull/13/files

2020-05-12 18:04 UTC, mathijshenquet submitted a review, later dismissed

2020-05-12 18:09 UTC, mathijshenquet requested changes
It would be preferable to have this reflect production. If you think this is out of scope for this PR we can merge it anyway.

2020-05-14 15:38 UTC, wolverdude commented
@mathijshenquet I've merged every other related PR. Please merge this as epimodel/master is broken until it is merged.

2020-05-14 15:38 UTC, merged